### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by 960801** [asgr/ProFound#21]
Hello.
I have followed the instructions on my ubuntu 20.04 on how to install ProFound.
I installed R using the command line, and when I try to install ProFound it fails and gives me an error :
bash: syntax error near unexpected token `'remotes''

how can I resolve this and get profound installed?
Thank you

**Comment by asgr** [comment]
Do you have the "remotes" package installed and loaded?

**Comment by 960801** [comment]
It had been a failure on my side to install remotes.
I've installed remotes, but get an error:
 download from 'https://api.github.com/repos/asgr/ProFound/tarball/HEAD' failed
when I run  :
 remotes::install_github("asgr/ProFound")

**Comment by asgr** [comment]
Did you set the environment and options are suggested in the readme? That error sounds related to those settings.

**Comment by 960801** [comment]
I had missed runing some of the stuff on the readme, I got it installed now.
Thank you.

**Comment by 960801** [comment]
Hello
I just needed some help with understanding this error when loading a fits image 

image = readFITS(system.file("extdata",'Abell_85_aFix_pol_I_15arcsec_5pln_cor_plane_freq.fits',package="ProFound"))
Error in if (nchar(inpString) != 2880) { : argument is of length zero
In addition: Warning messages:
1: In file(file, "rb") :
  file("") only supports open = "w+" and open = "w+b": using the former
2: In readChar(zz, 2880) :
  text connection used with readChar(), results may be incorrect

**Comment by asgr** [comment]
Two things:

readFITS is not my function (it is part of the FITSio package). It doesn’t support nearly as much of the FITS standard as Rfits, and you should therefore be using Rfits_read_image.

Second thing, you should just be providing a normal file path to your target FITS file, the system.file command is just an internal R method of accessing data included with the package.
