### ISSUE TITLE
Installation Issue on Ubuntu

### ISSUE THREAD

**Issue by hstewart93** [asgr/ProFound#23]
When installing ProFound using instructions in README, this error is encountered.

```
> remotes::install_github("asgr/ProFound")
Downloading GitHub repo asgr/ProFound@HEAD
Error: Failed to install 'ProFound' from GitHub:
  Line starting '<<<<<<< HEAD ...' is malformed!
```

Please can you advise, I have tried installing via devtools but this fails also.
Thank you!

**Comment by rtobar** [comment]
@hstewart93 this was a problem with the asgr/Rfits package actually, not ProFound itself. I just pushed a fix for the former, so if you try again you should get past this problem.

**Comment by hstewart93** [comment]
@rtobar Thank you for your quick response! I have successfully installed ProFound now.
