### ISSUE TITLE
ProFound on Radio data. 

### ISSUE THREAD

**Issue by natasha-lavis** [asgr/ProFound#24]
When applying ProFound to a radio image, the model of the source catalogue ends up with larger pixel values than the original image. 
Here the model has been defined as 

'''
segim_model=pro_out$group$groupim
model=(im$imDat-pro_out$sky)*segim_model 
'''
where pro_out is the output of profoundProFound. Any suggestions as to what is occurring here?

**Comment by asgr** [comment]
That can happen if the pro_out$sky is negative (often will be with real data).

**Comment by natasha-lavis** [comment]
Is there a solution to this problem though? Setting pro_out$sky to an absolute value does not resolve the problem.

**Comment by asgr** [comment]
I'm not sure I understand what the problem is. E.g. I don't understand why you'd want to multiply by groupim since this is not a binary mask (see ?profoundSegimGroup). Each group regions has the value of the lowest valued segID (so not just 0 or 1).

**Comment by natasha-lavis** [comment]
Thank you, I believe the problem has been resolved now by converting to a binary mask.
